
POST http://localhost:9090/register
Content-Type: application/json

{
  "username": "test_user02",
  "password": "Test@12345",
  "email": "test.user02@example.com",
  "name": "Test User2"
}


###
POST http://localhost:9090/login HTTP/1.1
content-Type: application/json

{
    "email": "test.user01@example.com",
    "password": "Test@1234"
    
    
}

###
POST http://localhost:9090/login HTTP/1.1
content-Type: application/json

{
    "email": "test.user02@example.com",
    "password": "Test@12345"
    
    
}
###

Get http://localhost:9090/get_user_and_profile HTTP/1.1
content-Type: application/json

{
   "token": "dcaeddcb23d4aa2dcf7eb130978cf089590b1941f8d62243464a6f04ddfe3187"
    
    
}

###
POST http://localhost:9090/update_profile_data HTTP/1.1
content-Type: application/json

{
   "token": "9fad0f17af9124c291f780c7c210b0b02f3a1aafd4460af72f117267215bcabc",
   "bio":"Hii I am Theja , I love Coding",
   "currentPost": "CTO",
   "pastwork":[
    {
      "company": "Microsoft",
      "position": "CTO",
      "years": "2+"
    }
   ],
   "education":[
    {
      "school":"III",
      "degree": "BCA",
      "fieldOfStudy": "2022-2025"
    }
   ]
    
}

###

Get http://localhost:9090/user/get_all_user_profiles 

###
Get http://localhost:9090/posts HTTP/1.1
###

POST http://localhost:9090/delete_post HTTP/1.1
content-Type: application/json

{
   "token": "670390736440879178a4220362c81c4911fb183ec3f7dddfacac4c9bb2a0dfb6",
   "post_id":"68709368a946bd00a7dbdbd2"
    
    
}